### ISSUE TITLE
GCSFuse + Docker Compose permissions

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/dams-deployment#2]
Currently in production we are having to run the `iiif` container in `privileged` mode.  There are examples online that say this should work but doesn't:

```
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - seccomp:unconfined
```
